# Generated by Django 3.0.3 on 2020-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200320_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_message',
            field=models.CharField(max_length=1000),
        ),
    ]
