# Generated by Django 3.0.3 on 2020-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200320_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_json', models.CharField(max_length=5000)),
                ('o_name', models.CharField(max_length=100)),
                ('o_num', models.CharField(max_length=15)),
                ('o_email', models.EmailField(max_length=100)),
                ('o_address', models.TextField()),
                ('o_from_date', models.DateTimeField()),
                ('o_to_date', models.DateTimeField()),
            ],
        ),
    ]
