# Generated by Django 3.0.3 on 2020-03-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='o_json',
            new_name='items_json',
        ),
    ]
