# Generated by Django 3.0.3 on 2020-04-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200321_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_amount',
            field=models.IntegerField(default=0),
        ),
    ]
